### ISSUE TITLE
Include Mosquitto in Bash-Script

### ISSUE THREAD

**Issue by marcolew** [IotStack-co/iotstack-bashscript#2]
Include Mosquitto in Bash-Script as part of the basic IoTStack. Mosquitto should be used for Device-Connectivity as kind of standard.

**Comment by marcolew** [comment]
If we might have different opinions on this, let's discuss first. I would like to see a standrad protocol being part of the stack.

**Comment by shantanoo-desai** [comment]
the next part of the scripts will be with `mosquitto` broker and other configuration files for `telegraf`. This is important since the telegraf configuration is dependent on the MQTT Brokers.

**Comment by ghost** [comment]
> the next part of the scripts will be with `mosquitto` broker and other configuration files for `telegraf`. This is important since the telegraf configuration is dependent on the MQTT Brokers.

You can use your working telegraf service to create a sample config for MQTT as an input to Telegraf and InfluxDB. `telegraf --input-filter mqtt_consumer --output-filter influxdb > telegraf.conf`.
When using the .deb or .rpm packages, you can define environment variables in the /etc/default/telegraf file. See [docs here](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md) for more info.

**Comment by shantanoo-desai** [comment]
@justenoughlinux you could have a look at [tiguitto](https:;//github.com/shantanoo-desai/tiguitto) which takes care of all the requirements
